version: '3.8'
services:  
  totem-api:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: totem-api
    container_name: 'totem-api'
    restart: always
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on: 
      - db
    networks:
      - totem
  db:
    image: postgres
    restart: always
    container_name: 'postgres'
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    networks:
      - totem
  
networks:
  totem:
    driver:
      bridge