apiVersion: v1
kind: Secret
metadata:
  name: fiap-totem-api-secret
type: Opaque
data:
  ConnectionStrings__DefaultConnection: SG9zdD1wb3N0Z3JlcztQb3J0PTU0MzI7RGF0YWJhc2U9VG90ZW1GaWFwO1VzZXJuYW1lPXBvc3RncmVzO1Bhc3N3b3JkPW15c2VjcmV0cGFzc3dvcmQ7SW5jbHVkZSBFcnJvciBEZXRhaWw9dHJ1ZQ==
  